package com.cn.taskmanagement.mapper;


import com.cn.taskmanagement.dto.ProjectDto;
import com.cn.taskmanagement.model.Project;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

/**
 * Mapper interface for converting between Project and ProjectDto.
 */
@Mapper
public interface ProjectMapper {

    // Singleton instance of the ProjectMapper generated by MapStruct
    ProjectMapper INSTANCE = Mappers.getMapper(ProjectMapper.class);

    /**
     * Converts a Project entity to a ProjectDto.
     *
     * @param project The Project entity to convert.
     * @return The corresponding ProjectDto.
     */
    ProjectDto projectToProjectDto(Project project);

    /**
     * Converts a ProjectDto to a Project entity.
     *
     * @param projectDto The ProjectDto to convert.
     * @return The corresponding Project entity.
     */
    Project projectDtoToProject(ProjectDto projectDto);
}
